@DotnetStockAPI_HostAddress = http://localhost:5160/api

###
GET {{DotnetStockAPI_HostAddress}}/Authenticate/testconnectdb/
Accept: application/json
###
# POST {{DotnetStockAPI_HostAddress}}/Authenticate/testconnectdb/
# Accept: application/json
# ###
# PUT {{DotnetStockAPI_HostAddress}}/Authenticate/testconnectdb/
# Accept: application/json
# ###
# DELETE {{DotnetStockAPI_HostAddress}}/Authenticate/testconnectdb/
# Accept: application/json
